### PR TITLE
Add Rails 6 support

### PR DESCRIPTION
**Pull request by n-rodriguez**
Thank you!

### CODE REVIEW

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
ping!

**Comment by prwhitehead** [comment]
Hello, is there any progress on this MR being merged in for Rails 6 support?

**Comment by n-rodriguez** [comment]
!?

**Comment by prwhitehead** [comment]
@n-rodriguez Would you consider forking with your Rails 6 branch and maintaining a new Repo that is maintained? 

Maybe emailing opensource@appfolio.com directly would get someone to review the MR?

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
ping @bboe

**Comment by bboe** [comment]
@n-rodriguez thanks for the direct ping. I should probably watch this repository. I'll take a look sometime today at this PR.

**Comment by n-rodriguez** [comment]
@bboe thank you!

**Comment by bboe** [comment]
Thanks for the PR. You are awesome! I am watching this repo now, so I should see updates.

**Comment by bboe** [comment]
Version 2.0.0 has been released. Thanks again for the great PRs!

**Pull request merged**
