### PR TITLE
Add Rails 6.1 support

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Review by bboe — APPROVED** [review]
Thanks for the continued efforts. I'll give this a merge once the tests finish. It looks like they stalled out.

**Comment by n-rodriguez** [comment]
Here the test results : https://github.com/n-rodriguez/store_base_sti_class/actions/runs/415808702 :rocket:

**Comment by n-rodriguez** [comment]
51s compared to the never ending Travis :rocket:

**Comment by bboe** [comment]
Perfect! Thanks for the update to github actions too. That's definitely preferred.

**Comment by n-rodriguez** [comment]
I forgot to update the badge in the README :/

**Comment by bboe** [comment]
Version 2.0.2 has been released. Thanks again!

**Comment by n-rodriguez** [comment]
Thank you!

**Pull request merged**
